# Generated by Django 4.1 on 2024-04-12 00:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("secondapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="cnt",
            new_name="cnt2",
        ),
    ]
