# Generated by Django 4.1 on 2024-04-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secondapp", "0003_rename_cnt2_course_cnt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArmyShop",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "army_shop",
                "managed": False,
            },
        ),
    ]
