# Generated by Django 4.1 on 2024-04-12 05:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("secondapp", "0004_armyshop"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="armyshop",
            options={},
        ),
    ]
