# Generated by Django 4.1 on 2024-04-12 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("secondapp", "0005_alter_armyshop_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="armyshop",
            options={"managed": False},
        ),
    ]
