# Generated by Django 4.1 on 2024-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum123",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name123", models.CharField(max_length=255)),
                ("age", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Curriculum",
        ),
    ]
