# Generated by Django 4.1 on 2024-04-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0003_curriculum_emp_delete_curriculum123"),
    ]

    operations = [
        migrations.CreateModel(
            name="member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
