# Generated by Django 4.1 on 2024-04-15 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0004_member"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="password",
            new_name="pwd",
        ),
    ]
